const MEMBERS = [
  { firstName: "Aaron", surname: "Gill", teamName: "Solve" },
{ firstName: "Aaron", surname: "Iny", teamName: "EY" },
{ firstName: "Aaron", surname: "Price", teamName: "Vancity" },
{ firstName: "Adam", surname: "Letendre", teamName: "Shinden" },
{ firstName: "Adam", surname: "Rollins", teamName: "Fountainhead" },
{ firstName: "Adrian", surname: "Pape", teamName: "EY" },
{ firstName: "Adrian", surname: "Prior", teamName: "Junction" },
{ firstName: "Ajit", surname: "Gaikwad", teamName: "Solve" },
{ firstName: "Alex", surname: "Balbino", teamName: "Forza" },
{ firstName: "Alexander", surname: "Starr", teamName: "Solve" },
{ firstName: "Alexandra", surname: "Tsardidis", teamName: "Fountainhead" },
{ firstName: "Alexandre", surname: "Pilon", teamName: "Pumpjack" },
{ firstName: "Allison", surname: "Coutts", teamName: "Numbers" },
{ firstName: "Alvan", surname: "Tam", teamName: "Pumpjack" },
{ firstName: "Anderson", surname: "Veiga", teamName: "Fountainhead" },
{ firstName: "Andras", surname: "Toth", teamName: "Forza" },
{ firstName: "Andres", surname: "Barboza", teamName: "QMUNITY" },
{ firstName: "Andrew", surname: "Fenton", teamName: "QMUNITY" },
{ firstName: "Andrew", surname: "Fong", teamName: "EY" },
{ firstName: "Andrew", surname: "Henwood", teamName: "Fanny Bay Oyster" },
{ firstName: "Andrew", surname: "Little", teamName: "Numbers" },
{ firstName: "Andrew", surname: "Mathias", teamName: "Vancity" },
{ firstName: "Andrew", surname: "Shirley", teamName: "EY" },
{ firstName: "Andrew", surname: "Thompson", teamName: "Shinden" },
{ firstName: "Andrew", surname: "Wilson", teamName: "Numbers" },
{ firstName: "Andrew", surname: "Wilson", teamName: "Junction" },
{ firstName: "Angus", surname: "Shaw", teamName: "Junction" },
{ firstName: "Anh Khoa", surname: "Vo", teamName: "Junction" },
{ firstName: "Anna", surname: "Davies", teamName: "Solve" },
{ firstName: "Annabelle", surname: "Breyley-Smith", teamName: "EY" },
{ firstName: "Antonio", surname: "Cerqueira", teamName: "EY" },
{ firstName: "Baraa", surname: "Orabi", teamName: "Solve" },
{ firstName: "Basel", surname: "Skeik", teamName: "Junction" },
{ firstName: "Bastien", surname: "Carobbio", teamName: "Forza" },
{ firstName: "Ben", surname: "Hirtz", teamName: "Pumpjack" },
{ firstName: "Ben", surname: "Montgomery", teamName: "EY" },
{ firstName: "Ben", surname: "Wells", teamName: "Shinden" },
{ firstName: "Binh", surname: "Nguyen", teamName: "Numbers" },
{ firstName: "Bradley", surname: "Breton", teamName: "Solve" },
{ firstName: "Brandon", surname: "Carless-Jones", teamName: "EY" },
{ firstName: "Brandon", surname: "Yan", teamName: "Numbers" },
{ firstName: "Brendan", surname: "Brauer", teamName: "Vancity" },
{ firstName: "Brendan", surname: "Sharp", teamName: "QMUNITY" },
{ firstName: "Brendon", surname: "McKenzie", teamName: "Forza" },
{ firstName: "Brennen", surname: "Musgrave", teamName: "Vancity" },
{ firstName: "Brian", surname: "Portner", teamName: "QMUNITY" },
{ firstName: "Brian", surname: "Zhang", teamName: "Fountainhead" },
{ firstName: "Bryan", surname: "Gidinski", teamName: "Fanny Bay Oyster" },
{ firstName: "Callum", surname: "Lowe", teamName: "Forza" },
{ firstName: "Cameron", surname: "Bourne", teamName: "Solve" },
{ firstName: "Cameron", surname: "Davitt", teamName: "Solve" },
{ firstName: "Carl", surname: "Oh", teamName: "Fanny Bay Oyster" },
{ firstName: "Carlo", surname: "Marcelo", teamName: "Pumpjack" },
{ firstName: "Carlos", surname: "Molina Hutt", teamName: "Fountainhead" },
{ firstName: "Charles", surname: "Keusters", teamName: "Forza" },
{ firstName: "Chris", surname: "Dancocks", teamName: "Fountainhead" },
{ firstName: "Chris", surname: "Flak", teamName: "Shinden" },
{ firstName: "Christopher", surname: "Russell", teamName: "Prince of Whales" },
{ firstName: "Christopher", surname: "Terreberry", teamName: "Prince of Whales" },
{ firstName: "Ciaran", surname: "Drain", teamName: "Pumpjack" },
{ firstName: "Clarence", surname: "Ng", teamName: "QMUNITY" },
{ firstName: "Clarice", surname: "Scop", teamName: "EY" },
{ firstName: "Cody", surname: "Profili", teamName: "Shinden" },
{ firstName: "Colby", surname: "Brose Duong", teamName: "Forza" },
{ firstName: "Cole", surname: "Armstrong", teamName: "Junction" },
{ firstName: "Cole", surname: "Sugden", teamName: "Pumpjack" },
{ firstName: "Colin", surname: "Gervais", teamName: "Numbers" },
{ firstName: "Connor", surname: "Marwick", teamName: "Solve" },
{ firstName: "Conor", surname: "Scholl", teamName: "Numbers" },
{ firstName: "Conor", surname: "Watters", teamName: "Fountainhead" },
{ firstName: "Cory", surname: "Genereaux", teamName: "Prince of Whales" },
{ firstName: "Cory", surname: "Wirth", teamName: "Forza" },
{ firstName: "Courtney", surname: "Crichton", teamName: "Solve" },
{ firstName: "Crisostomo", surname: "Gomez", teamName: "Solve" },
{ firstName: "Daniel", surname: "Bortoni", teamName: "Shinden" },
{ firstName: "Darcy", surname: "Paslawski", teamName: "Fanny Bay Oyster" },
{ firstName: "Dario", surname: "Evangelista", teamName: "Solve" },
{ firstName: "Darren", surname: "Moore", teamName: "Vancity" },
{ firstName: "David", surname: "Fryer", teamName: "QMUNITY" },
{ firstName: "David", surname: "Wiebe", teamName: "Numbers" },
{ firstName: "Dayton", surname: "Skei", teamName: "Fanny Bay Oyster" },
{ firstName: "Dedeker", surname: "Rondeau", teamName: "Shinden" },
{ firstName: "Derrick", surname: "Kalicum", teamName: "QMUNITY" },
{ firstName: "Derrick", surname: "Pham", teamName: "Fountainhead" },
{ firstName: "Dexter", surname: "Dusseault", teamName: "Fanny Bay Oyster" },
{ firstName: "Dmitry", surname: "Polunin", teamName: "Junction" },
{ firstName: "Edouard", surname: "Patoine", teamName: "Junction" },
{ firstName: "Elias", surname: "Alvarez Robles", teamName: "QMUNITY" },
{ firstName: "Ellie", surname: "Alvarez", teamName: "Shinden" },
{ firstName: "Emma", surname: "Cawood", teamName: "Fanny Bay Oyster" },
{ firstName: "Eoin", surname: "Cosgrove", teamName: "Fanny Bay Oyster" },
{ firstName: "Eric", surname: "Bagnall", teamName: "QMUNITY" },
{ firstName: "Eric", surname: "O Callaghan", teamName: "Fountainhead" },
{ firstName: "Eric", surname: "Towers", teamName: "Forza" },
{ firstName: "Eryn", surname: "Derksen", teamName: "Forza" },
{ firstName: "Evan", surname: "Doornberg", teamName: "Numbers" },
{ firstName: "Felipe", surname: "Quinonez", teamName: "Solve" },
{ firstName: "Felipe", surname: "Tavares da Cruz", teamName: "QMUNITY" },
{ firstName: "Fernando", surname: "Mercado", teamName: "Fountainhead" },
{ firstName: "Francis", surname: "Fernandez", teamName: "Vancity" },
{ firstName: "Francis", surname: "Yatco", teamName: "Prince of Whales" },
{ firstName: "Fraser", surname: "Hamilton", teamName: "Forza" },
{ firstName: "Galo", surname: "Oihartze", teamName: "Prince of Whales" },
{ firstName: "Geoff", surname: "Visser", teamName: "Shinden" },
{ firstName: "Geoffrey", surname: "Webb", teamName: "EY" },
{ firstName: "Gordon", surname: "Havelaar", teamName: "Shinden" },
{ firstName: "Graeme", surname: "Scott", teamName: "Pumpjack" },
{ firstName: "Graham", surname: "MacInnes", teamName: "Fountainhead" },
{ firstName: "Gregory", surname: "Sharp", teamName: "EY" },
{ firstName: "Guransh", surname: "Mann", teamName: "Forza" },
{ firstName: "Harry", surname: "Kim", teamName: "Solve" },
{ firstName: "Ian", surname: "Abuan", teamName: "Shinden" },
{ firstName: "Ibrahim", surname: "Yousef", teamName: "Vancity" },
{ firstName: "Isiah", surname: "Smith", teamName: "Junction" },
{ firstName: "Jack", surname: "Neill", teamName: "Fountainhead" },
{ firstName: "Jacob", surname: "Ruest", teamName: "Vancity" },
{ firstName: "Jaime", surname: "Schnurr", teamName: "Fanny Bay Oyster" },
{ firstName: "James", surname: "Ranson", teamName: "Prince of Whales" },
{ firstName: "James", surname: "Roberts", teamName: "Vancity" },
{ firstName: "Jared", surname: "Rudek", teamName: "Solve" },
{ firstName: "Jason", surname: "du Bourg", teamName: "Forza" },
{ firstName: "Jason", surname: "Falcao", teamName: "Numbers" },
{ firstName: "Jason", surname: "Roodbol", teamName: "Shinden" },
{ firstName: "Jason", surname: "Wilcox", teamName: "Solve" },
{ firstName: "Jaymes", surname: "Godkin", teamName: "Fountainhead" },
{ firstName: "Jean-Pierre", surname: "Calitz", teamName: "Numbers" },
{ firstName: "Jeffrey", surname: "Warren", teamName: "Vancity" },
{ firstName: "Jenna", surname: "Hildebrand", teamName: "Fanny Bay Oyster" },
{ firstName: "Jennifer", surname: "Campion", teamName: "Shinden" },
{ firstName: "Jenny", surname: "Kirby", teamName: "Prince of Whales" },
{ firstName: "Jere", surname: "Tarnowski", teamName: "QMUNITY" },
{ firstName: "Jeremy", surname: "Heppenstall", teamName: "Pumpjack" },
{ firstName: "Jesse", surname: "Johnson", teamName: "QMUNITY" },
{ firstName: "Jevon", surname: "Stimson", teamName: "QMUNITY" },
{ firstName: "Jillian", surname: "May", teamName: "Vancity" },
{ firstName: "Joan", surname: "Gamez guzman", teamName: "Pumpjack" },
{ firstName: "Joaquin", surname: "Acevedo", teamName: "Pumpjack" },
{ firstName: "Jobcel Isaac", surname: "Gacura", teamName: "Solve" },
{ firstName: "Joel", surname: "Ferstay", teamName: "Forza" },
{ firstName: "Joel", surname: "Kadziolka", teamName: "Numbers" },
{ firstName: "Joel", surname: "Newton", teamName: "Numbers" },
{ firstName: "John", surname: "Mundy", teamName: "Numbers" },
{ firstName: "Jonathan", surname: "Dawson", teamName: "Numbers" },
{ firstName: "Jonathan", surname: "Jackson", teamName: "Vancity" },
{ firstName: "Jonathan", surname: "Reich", teamName: "EY" },
{ firstName: "Jonathon", surname: "Braun", teamName: "EY" },
{ firstName: "Jono", surname: "Syron", teamName: "Junction" },
{ firstName: "Jordan", surname: "Brears", teamName: "Shinden" },
{ firstName: "Jordan", surname: "Heppenstall", teamName: "Pumpjack" },
{ firstName: "Jordan", surname: "Wagner", teamName: "Forza" },
{ firstName: "Jorge Andres", surname: "Avecias Aguilar", teamName: "Forza" },
{ firstName: "Joseph", surname: "Ferguson", teamName: "Prince of Whales" },
{ firstName: "Josh", surname: "Chen", teamName: "Prince of Whales" },
{ firstName: "Julian", surname: "Pradinuk", teamName: "Fountainhead" },
{ firstName: "Julie", surname: "Prodor", teamName: "Junction" },
{ firstName: "June", surname: "Diaz", teamName: "Vancity" },
{ firstName: "Kai", surname: "Okazaki", teamName: "Pumpjack" },
{ firstName: "Katherine", surname: "Madden", teamName: "Prince of Whales" },
{ firstName: "Katrina", surname: "De Ramos", teamName: "Fanny Bay Oyster" },
{ firstName: "Keith", surname: "O'Connor", teamName: "Junction" },
{ firstName: "Keith", surname: "Wyatt", teamName: "Prince of Whales" },
{ firstName: "Kevin", surname: "Craig", teamName: "QMUNITY" },
{ firstName: "Kevin", surname: "Pals", teamName: "Solve" },
{ firstName: "Kevin", surname: "Truong", teamName: "Vancity" },
{ firstName: "Kirat", surname: "Malik", teamName: "Fanny Bay Oyster" },
{ firstName: "Kleber", surname: "Ramires", teamName: "Vancity" },
{ firstName: "Kris", surname: "Jensen", teamName: "Shinden" },
{ firstName: "Kyle", surname: "Campbell", teamName: "Fanny Bay Oyster" },
{ firstName: "Kyle", surname: "Noftall", teamName: "Junction" },
{ firstName: "Kyle", surname: "Stapleton", teamName: "Fanny Bay Oyster" },
{ firstName: "Lanny", surname: "Pepler", teamName: "Forza" },
{ firstName: "Laura", surname: "Mathias", teamName: "Fanny Bay Oyster" },
{ firstName: "Lawrence Shane", surname: "Gordon", teamName: "EY" },
{ firstName: "Logan", surname: "Hunt", teamName: "Shinden" },
{ firstName: "Louisa", surname: "Lun", teamName: "EY" },
{ firstName: "Luc", surname: "McConnell", teamName: "Prince of Whales" },
{ firstName: "Lucas", surname: "Dornian", teamName: "Forza" },
{ firstName: "Lukas", surname: "Broscoe", teamName: "Forza" },
{ firstName: "Luke", surname: "Gruenhage", teamName: "QMUNITY" },
{ firstName: "Manuele", surname: "Pichierri", teamName: "Vancity" },
{ firstName: "Marc", surname: "Caringal", teamName: "Pumpjack" },
{ firstName: "Marcel", surname: "Benedetic", teamName: "Fountainhead" },
{ firstName: "Marcello", surname: "Brun del Re", teamName: "Numbers" },
{ firstName: "Marguerite", surname: "Prodor", teamName: "Numbers" },
{ firstName: "Mario", surname: "Botero", teamName: "Fountainhead" },
{ firstName: "Mark", surname: "Briand", teamName: "Fanny Bay Oyster" },
{ firstName: "Mark", surname: "Shepherd", teamName: "Forza" },
{ firstName: "Marty", surname: "Pilon", teamName: "Junction" },
{ firstName: "Mason", surname: "Margotta", teamName: "Pumpjack" },
{ firstName: "Matt", surname: "Berggren", teamName: "Junction" },
{ firstName: "Matt", surname: "Carruthers", teamName: "Fountainhead" },
{ firstName: "Matt", surname: "Hewitt", teamName: "Junction" },
{ firstName: "Matthew", surname: "Freed", teamName: "Shinden" },
{ firstName: "Matthew", surname: "Swanson", teamName: "Prince of Whales" },
{ firstName: "Mauricio", surname: "Blanco Gamboa", teamName: "Fanny Bay Oyster" },
{ firstName: "Max", surname: "Webber", teamName: "Fountainhead" },
{ firstName: "Michael", surname: "Brose Duong", teamName: "Fountainhead" },
{ firstName: "Michael", surname: "Jonasson", teamName: "Pumpjack" },
{ firstName: "Michael", surname: "Mah", teamName: "Fountainhead" },
{ firstName: "Michael", surname: "Mcleod", teamName: "Shinden" },
{ firstName: "Michael", surname: "Minkley", teamName: "EY" },
{ firstName: "Michael", surname: "Segovia", teamName: "Numbers" },
{ firstName: "Michael", surname: "Ton", teamName: "Solve" },
{ firstName: "Michael", surname: "Twamley", teamName: "Forza" },
{ firstName: "Michael", surname: "Wilkinson", teamName: "Junction" },
{ firstName: "Mihajlo", surname: "Zivanovic", teamName: "QMUNITY" },
{ firstName: "Miranda", surname: "McClure", teamName: "Numbers" },
{ firstName: "Montana", surname: "Allen", teamName: "Vancity" },
{ firstName: "Myles", surname: "Creed", teamName: "Pumpjack" },
{ firstName: "Nathan", surname: "Zec", teamName: "EY" },
{ firstName: "Neal", surname: "Adolph", teamName: "Vancity" },
{ firstName: "Niall", surname: "Coffey", teamName: "Prince of Whales" },
{ firstName: "Nicholas", surname: "Valencia", teamName: "Pumpjack" },
{ firstName: "Nick", surname: "Chenowith", teamName: "Prince of Whales" },
{ firstName: "Nick", surname: "Irvine", teamName: "Shinden" },
{ firstName: "Nicola", surname: "Spurling", teamName: "Prince of Whales" },
{ firstName: "Nikolai", surname: "Humniski", teamName: "Junction" },
{ firstName: "Owen", surname: "Rodger", teamName: "Junction" },
{ firstName: "Patric", surname: "McConnell", teamName: "Prince of Whales" },
{ firstName: "Patrick", surname: "Levesque", teamName: "Junction" },
{ firstName: "Paul", surname: "Cunningham", teamName: "Vancity" },
{ firstName: "Paul", surname: "Kot", teamName: "Fountainhead" },
{ firstName: "Paul", surname: "Lee", teamName: "Fanny Bay Oyster" },
{ firstName: "Pedro", surname: "Pessoa", teamName: "Junction" },
{ firstName: "Peter", surname: "Christiansen", teamName: "Prince of Whales" },
{ firstName: "Peter", surname: "Edelmann", teamName: "Fountainhead" },
{ firstName: "Peter", surname: "Truong", teamName: "QMUNITY" },
{ firstName: "Philip", surname: "Aristou", teamName: "Vancity" },
{ firstName: "Phillip", surname: "Tellier", teamName: "QMUNITY" },
{ firstName: "Pierce", surname: "Gorun", teamName: "QMUNITY" },
{ firstName: "Pom", surname: "Klomjaroon", teamName: "Pumpjack" },
{ firstName: "Rafe", surname: "Larsen", teamName: "Numbers" },
{ firstName: "Randy", surname: "Elliott", teamName: "EY" },
{ firstName: "Rey", surname: "Reynaldy", teamName: "Solve" },
{ firstName: "Riley", surname: "Bance", teamName: "EY" },
{ firstName: "Riley", surname: "Davidson", teamName: "Vancity" },
{ firstName: "Rob", surname: "Clarke", teamName: "QMUNITY" },
{ firstName: "Robin", surname: "Ellsworth", teamName: "Pumpjack" },
{ firstName: "Rodney", surname: "Zou", teamName: "Numbers" },
{ firstName: "Ronan", surname: "Duggan", teamName: "Fanny Bay Oyster" },
{ firstName: "Rory", surname: "Dubois", teamName: "Forza" },
{ firstName: "Ryan", surname: "Cheong", teamName: "EY" },
{ firstName: "Ryan", surname: "Hills", teamName: "Prince of Whales" },
{ firstName: "Ryan", surname: "Lee", teamName: "Pumpjack" },
{ firstName: "Ryan", surname: "Ward", teamName: "QMUNITY" },
{ firstName: "Sam", surname: "Holden", teamName: "EY" },
{ firstName: "Sam", surname: "Peters", teamName: "Solve" },
{ firstName: "Sam", surname: "Porta", teamName: "Solve" },
{ firstName: "Samantha", surname: "Morrow", teamName: "Vancity" },
{ firstName: "Samuel", surname: "Cullen", teamName: "EY" },
{ firstName: "Sara", surname: "Reimanis", teamName: "Prince of Whales" },
{ firstName: "Sasha", surname: "Sabinin", teamName: "QMUNITY" },
{ firstName: "Savo", surname: "Tomic", teamName: "QMUNITY" },
{ firstName: "Scott", surname: "Ferguson", teamName: "Prince of Whales" },
{ firstName: "Sean", surname: "Adair", teamName: "Prince of Whales" },
{ firstName: "Sean", surname: "Hayden", teamName: "Numbers" },
{ firstName: "Sean", surname: "Lessard", teamName: "Junction" },
{ firstName: "Senna", surname: "Van de Weygaert", teamName: "Fanny Bay Oyster" },
{ firstName: "Sergio", surname: "Villalobos Gilbert", teamName: "Shinden" },
{ firstName: "Shane", surname: "Inocencio", teamName: "Pumpjack" },
{ firstName: "Sian Hoe", surname: "Cheong", teamName: "Solve" },
{ firstName: "Sous", surname: "Oudomsouk", teamName: "Pumpjack" },
{ firstName: "Stephen", surname: "Scaccia", teamName: "Solve" },
{ firstName: "Steven", surname: "Ruggles", teamName: "Shinden" },
{ firstName: "Tamim", surname: "Arabi", teamName: "Numbers" },
{ firstName: "Tanner", surname: "Jones", teamName: "Forza" },
{ firstName: "Tasha", surname: "Lorenzen", teamName: "Fanny Bay Oyster" },
{ firstName: "Tatiana", surname: "San Martin", teamName: "Shinden" },
{ firstName: "Taylor", surname: "Fales", teamName: "Fanny Bay Oyster" },
{ firstName: "Taylor", surname: "Schmidt", teamName: "Shinden" },
{ firstName: "Terence", surname: "Chu", teamName: "Fanny Bay Oyster" },
{ firstName: "Thomas", surname: "Hilario", teamName: "Junction" },
{ firstName: "Thomas", surname: "Neufeld", teamName: "Shinden" },
{ firstName: "Thor", surname: "Eggertson", teamName: "Fanny Bay Oyster" },
{ firstName: "Tomas", surname: "Restrepo", teamName: "Fountainhead" },
{ firstName: "Tong", surname: "Zhu", teamName: "Vancity" },
{ firstName: "Troy", surname: "Johl", teamName: "Pumpjack" },
{ firstName: "Tyler", surname: "Johnston", teamName: "Prince of Whales" },
{ firstName: "Tyson", surname: "Phillips", teamName: "Numbers" },
{ firstName: "v", surname: "Doucette", teamName: "Forza" },
{ firstName: "Victor", surname: "Menendez", teamName: "QMUNITY" },
{ firstName: "Victoria", surname: "Carbol", teamName: "Pumpjack" },
{ firstName: "Vienna", surname: "Roberts", teamName: "Junction" },
{ firstName: "Vincent", surname: "Martin", teamName: "Pumpjack" },
{ firstName: "Vonn", surname: "Pedersen-Stewart", teamName: "Vancity" },
{ firstName: "Yohen", surname: "Thounaojam", teamName: "Prince of Whales" },
{ firstName: "Young", surname: "Zeng", teamName: "EY" },
{ firstName: "Zach", surname: "Nagel", teamName: "EY" },
{ firstName: "Zika", surname: "Trajkovic", teamName: "Fountainhead" }
];
